version: '2.1'
services:
  prometheus:
    networks:
      - abc
    image: prom/prometheus
    container_name: "prometheus"
    privileged: true
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules:/alertmanager/alert.rules
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '8081:9090'

  alertmanager:
    networks:
      - abc
    container_name: "alertmanager"
    image: prom/alertmanager
    privileged: true
    volumes:
      - ./alertmanager.yml:/alertmanager.yml
    command:
      - '--config.file=/alertmanager.yml'
    ports:
      - '8082:9093'
  
networks:
  abc:
    external: true

