global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'


rule_files:
  - /alertmanager/alert.rules

scrape_configs:
    
    
    - job_name: 'flight-details'
      metrics_path: '/flightdetails/metrics'
      static_configs:
        - targets: ['flightdetails:9090']

    - job_name: 'user-details'
      metrics_path: '/userdetails/metrics'
      static_configs:
        - targets: ['userdetails:7070']

    - job_name: 'reservation'
      metrics_path: '/reservation/metrics'
      static_configs:
        - targets: ['reservation:6060']

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']