version: '2.1'
services:
  flightdetails:
    networks:
      - abc
    image: flightdetails
    container_name: "flightdetails"
    ports:
     - "9090:9090"
    volumes:
      - ./logs:/flightdetails/logs
    links:
      - flightdetails-mysql
    depends_on:
      flightdetails-mysql:
                        condition: service_healthy
  flightdetails-mysql:
    networks:
      - abc
    image: mysql:5.7.17
    container_name: "flightdetails-mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DB=flightdetails
    healthcheck:
            test: "/usr/bin/mysql --user=root --password=test --execute \"SHOW DATABASES;\""
            interval: 2s
            timeout: 20s
            retries: 10
    ports:
      - "3308:3306"
networks:
  abc:
    external: true

