#!/bin/bash

dev()
{
rm -rf target
./mvnw clean package -DskipTests
docker build . -t flightdetails
docker network create abc
docker-compose -f docker-compose.yml up
}


usage() {
    echo "Usage: $0 dev"
    exit 1
}

CMD=${1:-}
SERVICE_NAME=${2:-}
shift || true
case ${CMD} in
  dev) dev;;
  *) usage ;;
esac
